export type ComponentSection = keyof typeof componentTitles;
export type DocsSection =
  'overview' | 'getting-started' | 'theming' | 'custom-components' | ComponentSection;
export const componentFamilies: readonly { name: string; sections: readonly ComponentSection[] }[] =
  [
    { name: 'Controls', sections: ['button', 'toolbar'] },
    {
      name: 'DataDisplay',
      sections: ['badge', 'codeblock', 'icon', 'mark', 'table', 'markdownpreview'],
    },
    { name: 'Feedback', sections: ['alert', 'toast', 'loader', 'progress'] },
    {
      name: 'Fields',
      sections: [
        'input',
        'textarea',
        'markdowneditor',
        'checkbox',
        'switch',
        'radio',
        'select',
        'slider',
      ],
    },
    { name: 'Layout', sections: ['layout'] },
    {
      name: 'Navigation',
      sections: ['accordion', 'breadcrumb', 'tabs', 'menu', 'dropdown', 'pagination', 'tree'],
    },
    { name: 'Surfaces', sections: ['card'] },
    { name: 'Visualization', sections: ['radarchart', 'linechart', 'barchart'] },
    { name: 'Overlays', sections: ['tooltip', 'popover', 'modal', 'drawer', 'floatingpanel'] },
  ];

export const componentTitles = {
  button: 'Button',
  toolbar: 'Toolbar',
  badge: 'Badge',
  codeblock: 'CodeBlock',
  icon: 'Icon',
  mark: 'Mark',
  table: 'Table',
  markdownpreview: 'MarkdownPreview',
  alert: 'Alert',
  toast: 'Toast',
  loader: 'Loader',
  progress: 'Progress',
  input: 'Input',
  textarea: 'TextArea',
  markdowneditor: 'MarkdownEditor',
  checkbox: 'Checkbox',
  switch: 'Switch',
  radio: 'Radio',
  select: 'Select',
  slider: 'Slider',
  layout: 'Layout',
  accordion: 'Accordion',
  breadcrumb: 'Breadcrumb',
  tabs: 'Tabs',
  menu: 'Menu',
  dropdown: 'Dropdown',
  pagination: 'Pagination',
  tree: 'Tree',
  card: 'Card',
  radarchart: 'RadarChart',
  linechart: 'LineChart',
  barchart: 'BarChart',
  tooltip: 'Tooltip',
  popover: 'Popover',
  modal: 'Modal',
  drawer: 'Drawer',
  floatingpanel: 'FloatingPanel',
} as const;
