import { buttonPresentation } from '@dreadnought/ui';
import { Button } from '@dreadnought/ui/react';
import { MarkdownEditor, type MarkdownEditorProps } from '@dreadnought/ui/react';
import { markdownEditorPresentation } from '@dreadnought/ui';
const markdownEditorProps: MarkdownEditorProps = { value: '', toolbar: false, labels: { bold: 'Bold' } };
import { MarkdownPreview, type MarkdownPreviewProps } from '@dreadnought/ui/react';
import { markdownPreviewPresentation } from '@dreadnought/ui';
const previewProps: MarkdownPreviewProps = { value: '# Hello' };
const liveProps: MarkdownEditorProps = { preview: 'live', historyLimit: 20, onPreviewChange: mode => void mode };
void [MarkdownPreview, markdownPreviewPresentation.root, previewProps, liveProps];
void [MarkdownEditor, markdownEditorPresentation.field, markdownEditorProps];
import { tabsPresentation } from '@dreadnought/ui';
import { Tabs } from '@dreadnought/ui/react';
import { TabsAdapter } from '@dreadnought/react/unstyled';
import { useTabs } from '@dreadnought/react/logic';
import { radarChartPresentation, getRadarSeriesClass } from '@dreadnought/ui';
import { RadarChart } from '@dreadnought/ui/react';
import type { RadarChartProps } from '@dreadnought/ui/react';
import { barChartPresentation, getBarSeriesClass } from '@dreadnought/ui';
import { BarChart, type BarChartProps } from '@dreadnought/ui/react';
const barProps: BarChartProps = { label: 'Bar', categories: [], series: [], domain: [0, 100] };
const barSeriesClass: string = getBarSeriesClass('__proto__');
void [barChartPresentation.root, barSeriesClass, BarChart, barProps];

const rootClass: string = buttonPresentation.root;
const component: typeof Button = Button;

void rootClass;
void component;
void tabsPresentation;
void Tabs;
void TabsAdapter;
void useTabs;
const radarSeriesClass: string = getRadarSeriesClass('__proto__');
const radarProps: RadarChartProps = { label: 'Radar', metrics: [], series: [] };
void [radarChartPresentation.root, radarSeriesClass, RadarChart, radarProps];
